### ISSUE TITLE
rename doesn't work for built in types

### ISSUE THREAD

**Issue by kayarre** [mcfarljm/fortwrap#1]
Getting the following warning

> Warning: REAL(dp) not supported

adding the following line to the config.i file doesn't change the behavior or the warning.
> %rename real(dp) real(c_double)

calling 
>~/code/fortwrap/fortwrap.py -i config.i  test.f90

**Comment by mcfarljm** [comment]
The `rename` configuration directive is for renaming either a function or derived type in the generated wrapper code, so it wouldn't have any effect here.

How are you defining `dp`?  Right now FortWrap will only recognize it if it is a literal integer constant, e.g.:
```
INTEGER, PARAMETER :: dp = 8
```

**Comment by kayarre** [comment]
Thank you so much for the reply. 

 I see I  clearly misunderstood the use case. Dp is mapped to c_double. I was able to just add that in the proper location in the type dictionary. However I still haven’t gotten it to generate wrappers. I need to mess with some more to figure out what I am doing wrong. The code I am working with makes Heavy use of more modern Fortran in some parts.
